{{- if eq (include "open-recognition.createDatabaseSecret" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-recognition.fullname" . }}
  labels:
    {{- include "open-recognition.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPEN_RECOGNITION_DATABASE_URL: {{ include "open-recognition.databaseUrl" . | quote }}
{{- end -}}
